users/urls.py
from django.urls import path
from .views import *

app_name = 'users'
urlpatterns = [
    path('hola/', hola, name='hola'),
    path('', inicio, name='inicio'),
    path('registrar-usuario', registerUser, name='register'),
    path('usuario-registrar', registrarUsuario, name='registrar'),
    path('usuarios-listar', listUsers, name='list'),
    path('usuario-actualizar/<int:pk>/', updateUser, name='update'),
    path('usuario-eliminar/<int:pk>/', deleteUser, name='delete'),
    path('usuarios-detalle-json/<int:pk>/', detailUserJson, 
        name='detail-json'),
    #: Vistas Genericas
    path('hola-mundo', HolaViews.as_view(), name='hola_mundo'),
    path('inicio-vista-generica', InicioViews.as_view(), 
        name='inicio_generico'),
    path('registro', CreateUserProfileView.as_view(), 
        name='registro_generico'),
    path('listar', ListUsersView.as_view(), name='listar_generico'),
    path('actualizar/<int:pk>/', UserUpdateView.as_view(), 
        name='actualizar_generico'),
    path('actualizar-perfil/<int:pk>/', UserProfileUpdateView.as_view(), 
        name='actualizar_perfil_generico'),
    path('eliminar-usuario/<int:pk>/', UserDeleteView.as_view(), 
        name='eliminar_generico'),
]

users/models.py
"""
ANALITICOM taller-django
"""
## @package users.models
#
# Model contiene los modelos de datos del users
# @author Team Analiticom-Mérida
# @date 08-04-2019
# @version 1.0

from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    """!
    Class modelo para almacenar los registro del pefil de usuario

    @author Ing. Leonel P. Hernandez M. (lhernandez at analiticom.com)
    @copyright ANALITICOM
    @date 08-04-2019
    @version 1.0.0
    """
    def get_upload_to(self, filename):
        return "perfil/%s/%s" % (self.fk_user.username, filename)
    #: Campo one to one a la tabla usuer de django
    fk_user = models.OneToOneField(User, on_delete=models.CASCADE)
    id_perfil = models.PositiveIntegerField(verbose_name='Documento de identidad', unique=True)
    foto = models.FileField(upload_to=get_upload_to, null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)

    class Meta:
        """!
            Clase meta data del modelo
        """
        ordering = ('fk_user',)
        verbose_name = 'User Profile'
        verbose_name_plural = 'Users Profiles'
        db_table = 'user_profile'

    def __str__(self):
        """!
        Function that shows the user's profile

        @return Devuelve el username del usuario
        """
        return self.fk_user.username

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from .models import *


class UserForm(UserCreationForm):
    """!
    Class que crea el formulario del usuario

    @author Ing. Leonel P. Hernandez M. (lhernandez at analiticom.com)
    @copyright ANALITICOM
    @date 08-04-2019
    @version 1.0.0
    """
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'email']

        def __init__(self, arg):
            super(UserForm, self).__init__()
            self.fields['first_name'].widget.attrs.update({'placeholder':
                                                           'Nombres'})
            self.fields['first_name'].required = True
            self.fields['last_name'].widget.attrs.update({'placeholder':
                                                          'Apellidos'})
            self.fields['last_name'].required = True
            self.fields['username'].widget.attrs.update({'placeholder':
                                                         'Nombre de usuario \
                                                         (Username)'})
            self.fields['username'].required = True
            self.fields['password1'].widget.attrs.update({'placeholder':
                                                          'Contraseña'})
            self.fields['password1'].required = True
            self.fields['password2'].widget.attrs.update({'placeholder':
                                                          'Repite la Contraseña'})

            self.fields['password2'].required = True
            self.fields['email'].widget.attrs.update({'class': 'form-control',
                                                      'placeholder': 'Email'})
            self.fields['email'].required = True

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        email = cleaned_data.get("email")

        if email:
            msg = "Error este email: %s, ya se encuentra asociado a una cuenta\
                  " % (email)
            try:
                User.objects.get(email=email)
                self.add_error('email', msg)
            except:
                pass


class UpdateUserForm(UserCreationForm):
    """!
    Class que crea el formulario del perfil de usuario

    @author Ing. Leonel P. Hernandez M. (lhernandez at analiticom.com)
    @copyright ANALITICOM
    @date 08-04-2019
    @version 1.0.0
    """
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'email']

        def __init__(self, arg):
            super(UserForm, self).__init__()
            self.fields['first_name'].widget.attrs.update({'placeholder':
                                                           'Nombres'})
            self.fields['first_name'].required = True
            self.fields['last_name'].widget.attrs.update({'placeholder':
                                                          'Apellidos'})
            self.fields['last_name'].required = True
            self.fields['username'].widget.attrs.update({'placeholder':
                                                         'Nombre de usuario \
                                                         (Username)'})
            self.fields['username'].required = True
            self.fields['password1'].widget.attrs.update({'placeholder':
                                                          'Contraseña'})
            self.fields['password1'].required = True
            self.fields['password2'].widget.attrs.update({'placeholder':
                                                          'Repite la Contraseña'})

            self.fields['password2'].required = True
            self.fields['email'].widget.attrs.update({'class': 'form-control',
                                                      'placeholder': 'Email'})
            self.fields['email'].required = True

class UserProfileForm(ModelForm):

    class Meta:
        model = UserProfile
        exclude = ['fk_user']

        def __init__(self, arg):
            super(UserProfileForm, self).__init__()
            self.fields['id_perfil'].widget.attrs.update({'placeholder':
                                                           'Identificador'})

users/views.py
"""
ANALITICOM taller-django
"""
## @package users.views
#
# View que contiene los controladores de los procesos de users
# @author Team Analiticom-Mérida
# @date 08-04-2019
# @version 1.0

import json
from django.contrib import messages
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core import serializers
from django.core.paginator import Paginator
from django.http import (
    HttpResponse, JsonResponse
)
from django.template import loader
from django.shortcuts import (
    render, get_object_or_404, redirect
)
#: Vistas genericas
from django.views import View
from django.views.generic import (
    TemplateView, ListView
)
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    UpdateView, DeleteView, FormView
)
from django.urls import reverse_lazy

from .decorators import verifyUsers
from .forms import *
from .models import *



def hola(request):
    """
    Funcion que responde Hola Mundo!
    
    @author Leonel P. Hernandez M. (lhenandez at analiticom.com)
    @date 08-04-2019
    @version 1.0
    """
    if request.method == 'GET':
        # desarrollar la logica del metodo
        return HttpResponse('Hola Mundo!')


def inicio(request, templates='inicio.html'):
    """
    Funcion que responde el template inicial del taller
    
    @author Leonel P. Hernandez M. (lhenandez at analiticom.com)
    @date 08-04-2019
    @version 1.0
    @params request objeto de la Peticion Http
    @params templates plantilla donde se rendreiza la respuesta
    @return objeto de la respuesta http
    """
    template = loader.get_template(templates)
    return HttpResponse(template.render({}, request))


def registerUser(request, templates='users/users.register.html'):
    """
    Funcion que responde el template para registrar un usuario, ademas resuelve la peticion por post cuando se llena el formulario
    
    @author Leonel P. Hernandez M. (lhenandez at analiticom.com)
    @date 08-04-2019
    @version 1.0
    @params request objeto de la Peticion Http
    @params templates plantilla donde se rendreiza la respuesta
    @return objeto de la respuesta http
    """
    template = loader.get_template(templates)
    if request.POST:
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        id_perfil = request.POST.get('id_perfil')
        foto = request.FILES
        descripcion = request.POST.get('descripcion')
        #: comprobar si existe o no el username 
        try:
            User.objects.get(username=username)
            messages.error(request, 
                           'Error el username: {0}, ya existe'.format(username)
                          )
            return HttpResponse(template.render({}, request))
        except:
            pass
        #: comprobar si existe o no el email 
        try:
            User.objects.get(email=email)
            messages.error(request, 
                           'Error el email: {0}, ya existe'.format(email))
            return HttpResponse(template.render({}, request))
        except:
            pass
        #: validar si las contraseñas son iguales
        if password1 == password2:
            #: validar password
            try:
                password_validation.validate_password(password1)
            except Exception as e:
                messages.error(request, ' '.join(e))
                return HttpResponse(template.render({}, request))
        else:
            messages.error(request, 'Error en las contraseña no son iguales')
            return HttpResponse(template.render({}, request))

        try:
            new_user = User.objects.create_user(
                username=username,
                first_name=first_name,
                last_name=last_name,
                email=email,
                password=password1,
                )
            new_user.set_password(password1)
            new_user.save()
        except Exception as e:
            messages.error(request, e)
            pass
        if foto:
            try:
                userprofile = UserProfile(
                    id_perfil=id_perfil,
                    descripcion=descripcion
                    )
                userprofile.fk_user = new_user
                userprofile.foto.save(foto['foto'].name, 
                                      foto['foto'].file, save=True)
                messages.success(request, 'Registro exitoso')
            except Exception as e:
                messages.error(request, e)
                pass
    return HttpResponse(template.render({}, request))


def registrarUsuario(request, templates='users/registrar.usuario.html', 
                     form=UserForm, form_profil=UserProfileForm):
    """
    Funcion que responde el template para registrar un usuario, ademas
    resuelve la peticion por post cuando se llenan los formularios
    
    @author Leonel P. Hernandez M. (lhenandez at analiticom.com)
    @date 08-04-2019
    @version 1.0
    @params request objeto de la Peticion Http
    @params templates plantilla donde se rendreiza la respuesta
    @params form objeto que contiene el formulario del usuario
    @params form_profil objeto que contiene el formulario del perfil de usuario
    @return objeto de la respuesta http
    """
    if request.POST:
        form = UserForm(request.POST)
        form_profil = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            new_user = form.save()
            if form_profil.is_valid():
                profile = form_profil.save(commit=False)
                profile.fk_user = new_user
                try:
                    profile.save()
                    messages.success(request, 'Registro exitoso')
                except Exception as e:
                    messages.error(request, 'Algo ocurre: {0}'.format(e))
        
    return render(request, templates, {'form': form, 
                                       'form_profil':form_profil})


@verifyUsers
def listUsers(request):
    """
    Funcion que lista los usuarios registrados 
    
    @author Leonel P. Hernandez M. (lhenandez at analiticom.com)
    @date 08-04-2019
    @version 1.0
    @params request objeto de la Peticion Http
    @return objeto de la respuesta http
    """
    user_list = User.objects.select_related()
    paginator = Paginator(user_list.order_by('pk'), 2) # Show 10 users per page

    page = request.GET.get('page')
    users = paginator.get_page(page)
    return render(request, 'users/list.users.html', {'users': users})


def updateUser(request, form=UpdateUserForm, 
               form_profil=UserProfileForm, *args, **kwargs):
    """
    Funcion que actualiza un usuario seleccionado
    
    @author Leonel P. Hernandez M. (lhenandez at analiticom.com)
    @date 08-04-2019
    @version 1.0
    @params request objeto de la Peticion Http
    @params form objeto que contiene el formulario del usuario
    @params form_profil objeto que contiene el formulario del perfil de usuario
    @return objeto de la respuesta http
    """
    instance = get_object_or_404(User, pk=kwargs['pk'])
    form = form(request.POST or None, instance=instance)
    instance_profile = get_object_or_404(UserProfile, fk_user=kwargs['pk'])
    form_profil = UserProfileForm(request.POST or None,
                                  request.FILES or None, 
                                  instance=instance_profile)
    if request.POST:
        if form.is_valid():
            new_user = form.save()
            if form_profil.is_valid():
                profile = form_profil.save(commit=False)
                profile.fk_user = new_user
                try:
                    profile.save()
                    messages.success(request, 'Registro exitoso')
                except Exception as e:
                    messages.error(request, 'Algo ocurre: {0}'.format(e))
    return render(request, 'users/update.user.html', 
                 {'form': form, 'form_profil':form_profil})


def deleteUser(request, *args, **kwargs):
    """
    Funcion que elimina un usuario seleccionado
    
    @author Leonel P. Hernandez M. (lhenandez at analiticom.com)
    @date 08-04-2019
    @version 1.0
    @params request objeto de la Peticion Http
    @return objeto de la respuesta http
    """
    user = get_object_or_404(User, pk=kwargs['pk'])
    user_profile = get_object_or_404(UserProfile, fk_user=kwargs['pk'])
    if request.POST:
        user.delete()
        user_profile.delete()
        messages.success(request, 'Se elimino con exitoso el usuario')
        user_list = User.objects.select_related()
        return redirect('users:list')
    return render(request, 'users/delete.user.html', {'user':user})


def detailUserJson(request, *args, **kwargs):
    """
    Funcion que muestra el detalle de un usuario seleccionado
    
    @author Leonel P. Hernandez M. (lhenandez at analiticom.com)
    @date 08-04-2019
    @version 1.0
    @params request objeto de la Peticion Http
    @return objeto Json con la respuesta
    """
    user = get_object_or_404(User, pk=kwargs['pk'])
    user_profile = get_object_or_404(UserProfile, fk_user=kwargs['pk'])
    
    serialized_object = serializers.serialize('json', [user])
    return JsonResponse(json.loads(serialized_object), safe=False)


#: Vistas basadas en clases

class HolaViews(View):
    """
    Vista basada en clase para controlar el metodo get
    """
    def get(self, request):
        """
        Metodo get, responde Hola Mundo!

        @author Leonel P. Hernandez M. (lhenandez at analiticom.com)
        @date 08-04-2019
        @version 1.0
        """
        # desarrollar la logica del metodo

users/templates/users/delete.user.html
{% extends 'inicio.html' %}
    {% block title %}Eliminar Usuario {% endblock title%}
    {% block content %}
        <h1>Eliminar Usuario</h1>
        <div>
            <form method="post">
                {% csrf_token %}
                Desea Eliminar el usuario: {{ user.username }}
                <button>Si</button>
            </form>
            <button onclick="location.href='{% url 'users:list' %}'">No</button>
        </div>
    {% endblock content %}
    

users/templates/users/list.users.html
{% extends 'inicio.html' %}
{% block title %}Lista de Usuarios {% endblock title%}
    {% block content %}
        <h1>Lista de Usuarios Registrados</h1>
        <ul class="object-tools">
          <li>
            <a href="{% url 'users:registrar' %}" class="addlink">
              Añadir User Profile
            </a>
          </li>          
        </ul>
        <table>
            <thead>
                <tr>
                    <th>
                        Username    
                    </th>
                    <th>
                        Nombres y apellidos    
                    </th>
                    <th>
                        Email    
                    </th>
                    <th>
                        Identificador    
                    </th>
                    <th>
                        Fecha de registro    
                    </th>
                    <th>
                        Ultima Conexion    
                    </th>
                    <th>
                        Se encuentra activo ?    
                    </th>
                    <th>
                        Foto de Perfil    
                    </th>
                    <th>
                        Descripcion    
                    </th>
                    <th>
                        Acciones    
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td><a href="{% url 'users:update' user.pk %}">{{ user.username }}</a></td>
                        <td>{{ user.first_name }} {{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.userprofile.id_perfil }}</td>
                        <td>{{ user.date_joined }}</td>
                        {% if user.last_login %}
                            <td>{{ user.last_login }}</td>
                        {% else %}
                            <td>Nunca ha iniciado sesion</td>
                        {% endif %}
                        {% if user.is_active %}
                            <td>Si</td>
                        {% else %}
                            <td>No</td>
                        {% endif %}
                        <td><a href="{{ MEDIA_URL }}{{ user.userprofile.foto }}">{{user.userprofile.foto}}</a></td>
                        <td>{{ user.userprofile.descripcion }}</td>
                        <td><a href="{% url 'users:delete' user.pk %}">Eliminar</a></td>
                    <tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="pagination">
            <span class="step-links">
                {% if users.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ users.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page 
                    {% if page_obj %}
                        {{ page_obj.number }} of {{ paginator.num_pages }}
                    {% else %}
                    {{ users.number }} of {{ users.paginator.num_pages }}.
                    {% endif %}
                </span>

                {% if users.has_next %}
                    <a href="?page={{ users.next_page_number }}">next</a>
                    <a href="?page={{ users.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
        {% if is_paginated %}
          <div class="pagination">
            {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            {% else %}
              <span>&laquo;</span>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <span>{{ i }} <span class="sr-only">(current)</span></span>
              {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            {% else %}
              <span>&raquo;</span>
            {% endif %}
          </div>
        {% endif %}
    {% endblock content %}

users/templates/users/registrar.usuario.html
{% extends 'inicio.html' %}
    {% block title %}Registrar Usuario {% endblock title%}
    {% block content %}
        <h1>Registrar Usuario</h1>
        <div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                {{form_profil.as_p}}
                <button>Registrar</button>
            </form>
        </div>
    {% endblock content %}
    

users/templates/users/update.user.html
{% extends 'inicio.html' %}
	{% block title %}Actualizar Usuario {% endblock title%}
    	{% block content %}
    		<h1>Actualizar Usuario</h1>
    		<div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                {{form_profil.as_p}}
                <button>Actualizar</button>
            </form>
        </div>
    	{% endblock content %}

users/templates/users/user_confirm_delete.html
{% extends 'inicio.html' %}
{% block title %} Eliminar Usuario {% endblock title %}
	{% block content %}
		<form method="post">
			{% csrf_token %}
    		<p>Estas seguro que quieres eliminar a "{{ object }}"?</p>
    	<input type="submit" value="Confirm">
</form>
	{% endblock content %}

users/templates/users/user_profile_update_form.html
{% extends 'inicio.html' %}
{% block title %} Actualizar Perfil de Usuari {% endblock title %}
	{% block content %}
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
		    	{{ form.as_p }}
		    <input type="submit" value="Update">
		</form>
	{% endblock content %}

users/templates/users/user_update_form.html
{% extends 'inicio.html' %}
{% block title %} Actualizar Usuario {% endblock title %}
	{% block content %}
		<form method="post">
			{% csrf_token %}
		    	{{ form.as_p }}
		    <input type="submit" value="Update">
		</form>
	{% endblock content %}

users/templates/users/users.register.html
{% extends 'inicio.html' %}
    {% block title %}Registrar Usuario {% endblock title%}
    {% block content %}
        <h1>Registrar Usuario</h1>
        <div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label>Username</label>
                <input type="text" name="username" placeholder="Username" required="true">
                <label>Nombre</label>
                <input type="text" name="first_name" placeholder="Nombres" required="true">
                <label>Apellido</label>
                <input type="text" name="last_name" placeholder="Apellidos" required="true">
                <label>Correo</label>
                <input type="text" name="email" placeholder="Correo Electronico" required="true"><br><br>
                <label>Contraseña</label>
                <input type="password" name="password1" placeholder="Contraseña" required="true">
                <label>Repite la Constraseña</label>
                <input type="password" name="password2" placeholder="Repite la contraseña" required="true"><br><br>
                <label>Numero de identificacion</label>
                <input type="text" name="id_perfil" placeholder="Identificador" required="true">
                <label>Foto de perfil</label>
                <input type="file" name="foto" accept="image/*">
                <label>Descripcion</label>
                <textarea name="descripcion"></textarea><br><br>
                <button>Registrar</button>
            </form>
        </div>
    {% endblock content %}
    